### ISSUE TITLE
[BUG] Page displays weirdly if you include a "/"  or "\" at the end of URL on /about route

### ISSUE THREAD

**Issue by Alan947** [ggkfox/CSCI-150#30]
Everything gets zoomed in and gets displayed in site map style.

**Comment by ABsolutelyWeb** [comment]
Not enough information. No idea what you're talking about.  Include a "/" or "\" where?

**Comment by Alan947** [comment]
If you include a "\" or "/" at the end of the url it causes that. Low probability the user will do that though.

**Comment by ABsolutelyWeb** [comment]
Like this? It appears it's rendering the raw page without the css.
![ex](https://user-images.githubusercontent.com/7468673/32576714-91c15892-c48c-11e7-8af9-69fc40298cff.PNG)

**Comment by ABsolutelyWeb** [comment]
I haven't tried it, but you could fix this by making another route in server.js called "/about/" that renders the about page.

**Comment by ABsolutelyWeb** [comment]
Oh! I figured it out! It's because the CSS that is needed for the /about route was temporarily placed inside the about.ejs file. So when we type "/about/", what's going on is that it's rendering the file, but it can't find the CSS. We will fix this later by making a separate CSS file for it. I never got around to doing it so I will do it soon. I actually made a separate issue about this to remind myself to do it. Once I do it, I will close that and this issue.
